### ISSUE TITLE
My RS485 can only send, but not receive.

### ISSUE THREAD

**Issue by Conmi-WhiteJoker** [steveohara/j2mod#134]
## Expected Behavior
Can read and write

## Actual Behavior
Only write, not read.
In fact, other RS485 tools can listen for the returned content, but the program itself does not receive the information.

Error info:
com.ghgande.j2mod.modbus.ModbusIOException: I/O failed to write
        at com.ghgande.j2mod.modbus.io.ModbusRTUTransport.writeMessageOut(ModbusRTUTransport.java:278)
        at com.ghgande.j2mod.modbus.io.ModbusSerialTransport.writeMessage(ModbusSerialTransport.java:109)
        at com.ghgande.j2mod.modbus.io.ModbusSerialTransport.writeRequest(ModbusSerialTransport.java:96)
        at com.ghgande.j2mod.modbus.io.ModbusSerialTransaction.execute(ModbusSerialTransaction.java:135)
        at com.ghgande.j2mod.modbus.facade.AbstractModbusMaster.readMultipleRegisters(AbstractModbusMaster.java:237)

## Steps to Reproduce the Problem
`serialParameters.setEncoding(Modbus.SERIAL_ENCODING_RTU);
serialParameters.setEcho(true);
serialParameters.setRs485Mode(true);`

## Specifications

  - Version:3.1.1
  - Platform:linux
  - Subsystem:Linux version 5.15.0-53-generic

**Comment by Conmi-WhiteJoker** [comment]
Solve, Sending must be set to "Odd"
